server:
  port: 8084

spring:
  application:
    name: pricing-service

  # ===============================
  # DATABASE (Pricing Rules, Audit)
  # ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/pricing_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: abhyas555
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # ===============================
  # REDIS (Surge Cache)
  # ===============================
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  # ===============================
  # KAFKA (Ride Events)
  # ===============================
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

    consumer:
      group-id: pricing-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

# ===============================
# EUREKA DISCOVERY
# ===============================
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# ===============================
# LOGGING
# ===============================
logging:
  level:
    root: INFO
    com.program: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# ===============================
# PRICING DEFAULTS
# ===============================
pricing:
  night:
    start-hour: 23
    end-hour: 5
    charge: 20.0

  surge:
    default-multiplier: 1.0
    redis-ttl-minutes: 10
